### ISSUE TITLE
peut-être expliquer le cas d'usage utilisé pour la démo

### ISSUE THREAD

**Issue by k33g** [idrissneumann/bdx-quickwit#2]

**Comment by idrissneumann** [comment]
C'est fait, merci beaucoup ^^

N'hésites pas à me dire ce que tu en penses :D

**Comment by k33g** [comment]
@idrissneumann top 👍 
j'ajouterais la signification d'APM pour les débutants

**Comment by idrissneumann** [comment]
Done, merci <3
